### ISSUE TITLE
Assembler

### ISSUE THREAD

**Issue by Bolivia123-stack** [Bolivia123-stack/BinaryC#1]
opcodes = {
    "ADD": "0001",
    "SUB": "0010",
    "MOV": "0011",
}
asm_code = input("Введите ассемблерный код: ")
instructions = asm_code.split("\n")
binary_code = ""
for instruction in instructions:
    opcode = opcodes[instruction.split(" ")[0]]
    binary_code += opcode
print("Бинарный код: " + binary_code)
print(binary_code)

**Comment by Sehktel** [comment]
Репозиторий пуст.
Как с этим работать?
Какие данные подаются на вход?
Какие данные получаются на выходе?
Как проверить работоспособность кода?

**Comment by Bolivia123-stack** [comment]
На вход подается ассемблерный код типа строки.
На выходе получаем бинарный код, соответствующий ассемблерному коду.
Чтобы проверить работоспособность кода, можно запустить его и ввести пример ассемблерного кода, например:
MOV A, 5
ADD A, 3
SUB A, 2

После этого программа должна вывести бинарный код для каждой инструкции в таком порядке: "MOV", "ADD", "SUB".

**Comment by Sehktel** [comment]
https://github.com/Bolivia123-stack/BinaryC
**This repository is empty.**
![image](https://user-images.githubusercontent.com/24711055/236735738-475c6b93-39f7-4b0c-a8c3-0563b4fc37cb.png)
